### ISSUE TITLE
请问如何安装    直接下载的话    文件缺少报错

### ISSUE THREAD

**Issue by wikiInit** [pljhonglu/LewPhotoBrowser#1]

**Comment by pljhonglu** [comment]
项目使用了 CocoaPods，请先安装依赖，使用方法请见：https://cocoapods.org/

**Comment by wikiInit** [comment]
pods LewPhotoBrowser  ？   不存在呀

**Comment by pljhonglu** [comment]
LewPhotoBrowser 并没有提交到 pod Specs 因此无法使用CocoaPods直接安装，请下载项目，直接把所需要的文件添加到自己的项目中。
